#!/bin/bash

current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
installation_directory="${XDG_CONFIG_HOME:-${HOME}/.config}/desktop_scripts"
mkdir -p $installation_directory
echo 'export PATH="$PATH:'"$current_dir/scripts\"" > "${installation_directory}/config"

