#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys
import datetime

import cv2


def capture_video(camera_id):
    video_cap = cv2.VideoCapture(camera_id)
    video_cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
    video_cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

    while True:
        _, current_frame = video_cap.read()
        cv2.imshow('Video', current_frame)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('s'):
            date_time = datetime.datetime.now().strftime('%y%m%d%H%M%S')
            file_name = 'frame_{0}.jpg'.format(date_time)
            cv2.imwrite(file_name, current_frame)
            print('Saved image {0}'.format(file_name))
        elif key == ord('q'):
            break

    video_cap.release()
    cv2.destroyAllWindows()


def main():
    if len(sys.argv) > 1:
        camera_id = int(sys.argv[1])
    else:
        camera_id = 0
    capture_video(camera_id)

if __name__ == "__main__":
    main()
